export const GET_COURSES = "courses/GET_COURSES";
export const GET_ONE_COURSE = "courses/GET_ONE_COURSE";
export const GET_CATEGORIES_WITH_COURSE = "courses/GET_CATEGORIES_WITH_COURSE";
export const GET_ONE_CATEGORIES_WITH_COURSE =
  "courses/GET_ONE_CATEGORIES_WITH_COURSE";

export const GET_BOOKINGS = "bookings/GET_BOOKINGS";
export const GET_ONE_BOOKINGS = "bookings/GET_ONE_BOOKINGS";

export const GET_SCHEDULE = "schedule/GET_SCHEDULE";

export const GET_ONE_INSTRUCTOR = "GET_ONE_INSTRUCTOR";
export const GET_INSTRUCTOR = "GET_INSTRUCTOR";
export const LOGIN_INSTRUCTOR = "LOGIN_INSTRUCTOR";
